import type { ClientConfig } from '../types';

// Replace the sample content here for each client. Product order is display order.
export const client = {
  demo: {
    enabled: true,
    label: 'PRODUCT CATALOGUE',
    note: 'Created by Alvin · Fictional business',
  },
  business: {
    name: 'Common Form',
    monogram: 'CF',
    location: 'Calgary, Alberta',
  },
  seo: {
    title: 'Common Form — Useful objects for everyday spaces',
    description: 'A sample product catalogue for a modern independent shop.',
    language: 'en-CA',
    indexable: false,
  },
  ui: {
    skipToContent: 'Skip to content',
    menuOpen: 'Menu',
    menuClose: 'Close',
    navigationLabel: 'Main navigation',
    backToTop: 'Back to top',
    allProducts: 'All',
    productCount: 'shown',
  },
  navigation: [
    { label: 'Shop', href: '#products' },
    { label: 'Our approach', href: '#story' },
    { label: 'Contact', href: '#contact' },
  ],
  headerAction: { label: 'View collection', href: '#products' },
  hero: {
    eyebrow: 'THE SPRING EDIT / 2026',
    title: 'Objects for',
    titleAccent: 'slower living.',
    description: 'A small collection of tactile, useful pieces selected to bring ease, warmth, and quiet character to the everyday.',
    primaryAction: { label: 'Shop the collection', href: '#products' },
    secondaryAction: { label: 'Why we chose them', href: '#story' },
    image: {
      src: 'images/common-form-lamp.webp',
      alt: 'Cobalt ceramic table lamp with a navy fabric shade on a white plinth.',
      width: 1254,
      height: 1254,
    },
    featuredLabel: ' THE HOME EDIT',
    featuredName: 'Column lamp',
    featuredPrice: '$148 CAD',
  },
  catalogue: {
    eyebrow: 'CURATED FOR EVERYDAY',
    title: 'The considered collection.',
    description: 'Simple forms, honest materials, and details that reward daily use. Browse the edit by the way each piece lives with you.',
    categories: [
      { id: 'home', label: 'Home' },
      { id: 'table', label: 'Table' },
      { id: 'carry', label: 'Carry' },
    ],
    products: [
      {
        id: 'column-lamp',
        name: 'Column lamp',
        category: 'home',
        description: 'Glazed ceramic, a woven shade, and warm task light for quieter corners.',
        price: '$148 CAD',
        badge: 'Featured',
        details: ['Glazed ceramic', 'Woven linen', 'Warm LED'],
        image: {
          src: 'images/common-form-lamp.webp',
          alt: 'Cobalt ceramic table lamp with a navy fabric shade.',
          width: 1254,
          height: 1254,
        },
        action: { label: 'View product', href: '#contact' },
      },
      {
        id: 'fold-tray',
        name: 'Fold tray',
        category: 'table',
        description: 'Powder-coated steel with low edges and integrated handles.',
        price: '$64 CAD',
        details: ['Powder-coated steel', 'Hand finished'],
        image: {
          src: 'images/common-form-tray.webp',
          alt: 'Coral powder-coated rectangular metal tray.',
          width: 1254,
          height: 1254,
        },
        action: { label: 'View product', href: '#contact' },
      },
      {
        id: 'carry-all',
        name: 'Carry all',
        category: 'carry',
        description: 'Heavy cotton canvas with a structured base and generous handles.',
        price: '$78 CAD',
        badge: 'New',
        details: ['14 oz cotton canvas', 'Reinforced base'],
        image: {
          src: 'images/common-form-tote.webp',
          alt: 'Structured midnight-blue canvas tote bag with coral lining.',
          width: 1254,
          height: 1254,
        },
        action: { label: 'View product', href: '#contact' },
      },
      {
        id: 'angle-mug',
        name: 'Angle mug',
        category: 'table',
        description: 'Glazed stoneware with a balanced geometric handle and deep interior.',
        price: '$38 CAD',
        details: ['Glazed stoneware', '350 ml'],
        image: {
          src: 'images/common-form-mug.webp',
          alt: 'Cobalt ceramic mug with an angular handle and coral foot.',
          width: 1254,
          height: 1254,
        },
        action: { label: 'View product', href: '#contact' },
      },
    ],
  },
  story: {
    eyebrow: 'MATERIALS, MADE CLEAR',
    title: 'Fewer things. Better reasons.',
    body: 'We choose pieces for how they feel, how they function, and how gracefully they settle into a space. Every finish and fibre is listed plainly, so the story behind an object is as considered as the object itself.',
    image: {
      src: 'images/common-form-tote.webp',
      alt: 'Midnight-blue canvas tote photographed against a clean white backdrop.',
      width: 1254,
      height: 1254,
      position: '50% 38%',
    },
    action: { label: 'Explore the collection', href: '#products' },
    details: [
      { label: 'Selection', value: 'Small, seasonal edits' },
      { label: 'Materials', value: 'Clearly documented' },
      { label: 'Origin', value: 'Independent makers' },
    ],
  },
  highlights: [
    { title: 'Small runs', description: 'Focused collections with room for thoughtful details.' },
    { title: 'Clear materials', description: 'Simple descriptions help customers know what they are buying.' },
    { title: 'Flexible fulfilment', description: 'Link products to your shop, booking page, or enquiry form.' },
  ],
  contact: {
    eyebrow: 'QUESTIONS / STOCKISTS',
    title: 'Need a closer look?',
    description: 'Ask about an item, current availability, local pickup, or wholesale orders.',
    action: { label: 'Email the shop', href: 'mailto:hello@example.com' },
    details: ['Calgary pickup available', 'Ships across Canada', 'Tuesday–Saturday'],
  },
  footer: {
    note: 'Useful objects for everyday spaces.',
    copyright: 'Common Form is a fictional business. Product imagery was generated for this demonstration.',
    links: [],
  },
} satisfies ClientConfig;
